// Informacija is svetaines https://www.finaura.lt/?p=269
var frazes = [
  '<span style="font-size: small;">Didžiausia klasikinių kūrinių vertybė ta, kad jie įkvepia išmintingiems pašnekesiams, rimtiems ir nuoširdiems pokalbiams, apmąstymams.</span><br><span style="font-size: small;"> Anatolis Fransas</span>',
  "Galbūt aš nenuėjau ten, kur ketinau, bet už tat sustojau ten, kur norėjau.<br>Duglasas Adamsas",
  "Nė dienos nenukrypk nuo savo tikslo – štai būdas prailginti laiką, be to, būdas labai geras, nors naudotis juo ir nelengva.<br>Džordžas Kristofas Lichtenbergas",
  "Mes gyvename iš to, ką gauname, bet kuriame gyvenimą iš to, ką duodame.<br>V. Čerčilis",
  "Reikia nugyventi ilgą gyvenimą ir pasenti, kad suprastum, koks jis trumpas.<br>A. Šopenhaueris",
  "Didžiausią reikšmę gyvenime turi tai, ką padarote dėl kitų.<br>Zigas Ziglaras",
  "Kai gyvenime viskas kontroliuojama, dažniausiai nebelieka ką kontroliuoti, – nebelieka pačios gyvybės.<br>Klarisa Pinkola Estes",
  "Gyvenimui reikia judesių.<br>Aristotelis",
  "Nebandykite gyventi amžinai, jums nieko neišeis.<br>Džordžas Bernardas Šo",
  "Gyvenimas – menas visur surasti grožį ir džiaugsmą.<br>Maksimas Gorkis",
  "Jei nori gyventi sau, gyvenk kitiems.<br>Seneka",
  "Mokytam ir išsilavinusiam žmogui gyventi – lygu mąstyti.<br>Ciceronas",
  "Gyvenimas yra tai, kas vyksta, kol jūs esate užsiėmęs kitais darbais.<br>Džonas Lenonas",
  "Visi nori gyventi ilgai, bet niekas nenori pasenti.<br>Dž. Sviftas",
  "Gyvenimas užkrečiamas – kaip ir liga.<br>Ž. Sandas",
  "Žmogus visą gyvenimą praleidžia tikėdamasis ir miršta dar turėdamas vilties.<br>Volteras",
  "Gyvenimas – tai kalnas: kopiame lėtai, žemyn lipame greitai.<br>Gi de Mopasanas",
  "Nesielk taip, lyg gyvenimas truktų tūkstančius metų.<br>Markas Aurelijus",
  "Kas turi kam gyventi, ištvers bet kokį kaip.<br>Frydrichas Nyčė",
  "Jei nori gyventi laimingą gyvenimą – susiek jį su tikslu, o ne su kitais žmonėmis ar daiktais.<br>A. Einšteinas",
  "Gyvenime nėra kursų pradedantiesiems: kiekvienas iš karto gauna sunkiausius uždavinius.<br>R.M. Rilke",
  "Spręsti apie žmogaus gyvenimo prasmę neįmanoma iš jo trukmės. Juk skaitomą biografiją irgi vertiname ne pagal jos “ilgį”, knygos puslapių skaičių, o pagal turiningumą.<br>Viktoras Emilis Franklas",
  "Jei gyvenimas apskritai turi prasmę, tai prasmę privalo turėti ir kančia. Juk kančia irgi yra gyvenimo dalis – kaip ir likimas, ir mirtis. Tik kančia ir mirtis paverčia žmogaus būtį visuma.<br>B.Franklinas",
  "Žmonės labai anksti suvokia savo gyvenimo prasmę, – sako senis, ir jo akyse atsispindi keistas liūdesys. – Gal todėl jie taip pat anksti jos ir išsižada.<br>Paulo Coelho",
  "Kai gyventi gera, nėra reikalo ginčytis dėl gyvenimo prasmės.<br>Rėjus Bredberis",
  "Iš tikrųjų gyvenime nėra mažų ar didelių dalykų. Visa yra vienodai reikšminga, visa lygiai didu.<br>Oskaras Vaildas",
  "Netekti gyvybės- menkas dalykas. Bet matyti kaip tavo gyvenimas netenka prasmės,kaip nyksta mūsų gyvenimo tikslas-štai kas nepakeliama.<br>Alberas Kamiu",
  "Svajonės suteikia pasauliui įdomumą ir prasmę. Nuoseklios ir protingos svajonės tampa dar gražesnės, kai kuria realų pasaulį pagal savo paveikslą ir panašumą.<br>Anatolis Fransas",
  "Meilė yra pagrindinis raktas nuo laimės vartų.<br>Oliveris Vendelis Holmes",
  "Meilė, tai ugnies apimta draugystė.<br>Jeremis Tailoras",
  "Meilė – tai neatsispiriamas troškimas būti neatsispiriamai troškiamu.<br>Robertas Frostas",
  "Meilė yra tokia būsena, kai kito laimė yra būtina tavąjai.<br>Robertas A. Heinleinas",
  "Aš ją myliu, ir tai yra visko pradžia bei visko pabaiga.<br>F. Skotas Fitzgeraldas",
  "Meilė – sielos grožis.<br>Šv. Augustinas",
  "Mylėti reiškia išvysti rojaus švystelėjimą.<br>Karenas Sunde",
  "Tikra meilė prasideda tada, kai nieko nesitikima už ją gauti.<br>Antoine De Saint-Exupery",
  "Tik meilė žino paslaptį, kaip apdovanojant kitą, praturtėti pačiam.<br>C. Brentano",
  "Jei myli žmogų, vadinasi, sutinki su juo pasenti.<br>A. Camus",
  "Vien tik todėl, kad kažkas nemyli tavęs taip, kaip tau norisi, dar nereiškia, kad jis nemyli tavęs iš visos širdies.<br>G.G.Markuezas",
  "Kai tu esi šalia man užima kvapą, ir negaliu ištarti nieko, ką noriu tau pasakyti. Tada, tyloje, man belieka tikėtis, kad mano akys kalbės už širdį.<br>Robertas Sekstonas",
  "Pačių nuostabiausių dalykų pasaulyje negalima pamatyti ar paliesti. Juos reikia pajusti širdimi.<br>Helena Keler",
  "Meilė – vienintelis dalykas, kuris eikvojamas auga.<br>R. Huchas",
  "Gyvenime yra du tikri džiaugsmai – mylėti ir būti mylimam.<br>G. Sandas",
  "Išmokti mylėti įmanoma tik mylint.<br>I. Murdochas",
  "Meilė yra tame, kuris myli, o ne tame, kurį myli.<br>Irvinas D. Jalomas",
  "Meilė leidžia išgyventi kitą, kaip pasaulį savyje, taip išplėsdama ir mūsų pasaulį.<br>Viktoras Emilis Franklis",
  "Mylėti – reiškia norėti kitam to, ką laikai gėrybe; be to, norėti ne savo labui, o to, kurį myli, ir stengtis pagal išgales suteikti jam tą gėrybę.<br>Aristotelis",
  "Draugystė, kuri pasibaigė, niekuomet iš tikro nebuvo prasidėjusi.<br>Publijus Siras",
  "Mylėjimas yra išgyvenimas, o draugystė – nuostata. Mat mylėti galima ir negyvus daiktus, o abipusė draugystė galima tik sąmoningai pasirinkus; sąmoningą pasirinkimą lemia sielos nuostata. Vadovaudamiesi ne aistra o nuostata, žmonės savo mylimiesiems linki gero dėl jų pačių, o mylėdami draugą myli tai, kas jiems patiems yra gera.<br>Aristotelis",
  "Veiksmai, o ne žodžiai, yra tikros draugystės matas.<br>Džordžas Vašingtonas",
  "Iš visko, ką išmintis mums siūlo laimingam gyvenimui sukurti, pats didžiausias dalykas puoselėti draugystę.<br>Epikūras",
  "Draugas yra dovana, kurią pats sau įteiki.<br>R. L. Stivensonas",
  "Draugą aš labiausiai myliu už jo trūkumus, apie kuriuos galima pakalbėti.<br>V. Hazlitas",
  "Tikras draugas turi būti antruoju mūsų „aš“; jis niekuomet nepareikalaus iš draugo nieko, išskyrus tai, kas dorovinga ir puiku; draugystė mums duota iš prigimties kaip kilnumo pagalbininkė, bet ne kaip ydų palydovė.<br>Ciceronas",
  "Draugystė ir neįkainojama, ir nuostabi: mes garbstome tą, kuris myli savo draugus, ir turėti daug draugų atrodo labai gražu, o kai kas net mano, kad būti geru žmogumi ir draugu – tolygu.<br>Aristotelis",
  "Draugystė nėra būtinybė – kaip ir filosofija ar menas. Draugystė neturi išliekamosios vertės. Veikiau ji yra vienas iš tų dalykų, kurie suteikia vertę išlikimui.<br>C.S. Levisas",
  "Draugystės nesumenkina nei atstumas, nei laikas, nei nelaisvė, nei karas, nei kančia, nei tyla. Kaip tik į šią dirvą ji giliausiai suleidžia šaknis. Ir šioje dirvoje ji pražysta.<br>Pamas Braunas",
  "Šeima – vienas iš gamtos šedevrų.<br>D. Santajana",
  "Geriausi dalykai, nutinkantys jums, ir geriausia, ką padarote jūs, atliekama “dėl meilės”. Štai kodėl sakau, kad geri santykiai šeimoje paskatina jus aukštesniems sėkmės lygiams. Sėkmė iš tiesų prasideda namuose.<br>Zigas Ziglaras",
  "Šeima– tai miniatiūrinė visuomenė, nuo kurios vientisumo priklauso visos didelės visuomenės saugumas.<br>F.Adleris",
  "Šeima – tai bendrija, susidedanti iš pono, ponios ir dviejų vergų – iš viso iš dviejų žmonių.<br>A. Birsas",
  "Būtinai vesk. Jei gausi gerą žmoną, būsi laimingas; jei blogą – tapsi filosofu.<br>Sokratas",
  "Sėkmė šeimoje priklauso nuo prasmingų pokalbių su sutuoktiniais ir vaikais. Nutrauk šiuos pokalbius, ir šeimos nebeliks.<br>Robinas Sharma",
  "Mūsų svajonių įgyvendinimas yra įkvėpimo šaltinis naujiems mūsų sumanymams.<br>Orizonas Svetas Mardenas",
  "Svajonė – tai žmogaus veržimasis pirmyn, tai visos jo viltys, visos jo paslaptys.<br>H. Seidbeilis",
  "Svajoti, vadinasi, kurti.<br>V. Hugo",
  "Žmogus be svajonės – lakštingala be balso.<br>M. Stelmachas",
  "Jei sugriautume visas žmonių svajones ir iliuzijas, pasaulis prarastų savo formas ir spalvas, o mes amžiams liktume buki ir kvaili.<br>A. Fransas",
  "Mums svarbiausia tai, kad mes galime paversti savo svajones realybe.<br>Vadimas Zelandas",
  "Svajonės yra būtinos gyvenimui.<br>Anais Nin",
  "Niekas nevyksta, išskyrus kai atsiranda svajonė.<br>Karlas Sandburgas",
  "Svajones žlugdo vienintelis dalykas – kompromisai.<br>Ričardas Bachas",
  "Aš supratau, kad žmogus, turintis didelių svajonių, yra galingesnis už tą, kuris turi tik daug faktų ir žinių.<br>H.J. Braunas",
  "Svajok taip, tarsi būtum nemirtingas, o gyvenk taip, tarsi mirtum šiandien.<br>Džeimsas Dynas",
  "Didžio svajotojo svajonės visada išsipildo su kaupu.<br>Alfredas Nortas Vaithedas",
  "Galimybė įgyvendinti svajonę – štai kas gyvenimą daro įdomų.<br>Paulo Coelho",
  "Jeigu Jūs galite apie tai svajoti, tai jūs galite tai padaryti.<br>Voltas Disnėjus",
  "Kovok už savo svajones ir tavo svajonės kovos už tave.<br>Paulo Coelho",
  "Laimingas tas, kuris sutaria su savimi ir aplinkiniais.<br>O. Vaildas",
  "Laimė beldžiasi mažiausiai kartą į kiekvienas duris.<br>Viljamas Gezlitas",
  "Tik bendroje laimėje galima rasti savo asmeninę laimę.<br>Tomas Hobsas",
  "Laimę gali turėti tik tol, kol jos nematai.<br>H. Hesas",
  "Nori būti laimingas visą gyvenimą – būk sąžiningas žmogus.<br>Tomas Fuleris",
  "Jeigu būtų statomi laimės namai, pačią didžiausią patalpą reikėtų skirti laukiamajam.<br>Ž. Renaras",
  "Laimė – kaip sveikata: jeigu jos nepastebi, vadinasi, ji yra.<br>I. Turgenevas",
  "Dauguma žmonių sieja laimę su tam tikromis sąlygomis. Tačiau patirti laimę galima tik nekeliant jokių sąlygų.<br>A. Rubinsteinas",
  "Žmogaus gyvenimas kupinas laimės daugiausia dėl to, kad žmogus amžinai laukia, jog netrukus bus laimingas.<br>E. A. Po",
  "Didelei laimei reikia ir kilnios sielos.<br>Publijus Siras",
  "Dauguma žmonių turi tiek laimės, kiek patys nori turėti.<br>A. Linkolnas",
  "Žmogus negali būti laimingas be laisvės.<br>Dantė",
  "Laimė ir moralinė pareiga yra neatskiriamai sujungtos.<br>Džordžas Vašingtonas",
  "Mūsų laimei daug svarbiau tai, kas mes esame, o ne ką mes turime.<br>Artūras Šopenhaueris",
  "Kiekvienas, norintis būti laimingas, privalo išmokti branginti išmintį ir trokšti suprasti, ką jis čia, šioje planetoje, veikia.<br>Robinas Sharma",
  "Laimingas tas, kuris džiaugsmingai dirba ir džiaugiasi darbais, kuriuos padarė.<br>J. V. Gėtė",
  "Neįsivaizduok, kad tu galėtum būti laimingas, o drauge ir tinginys. Laimė ir veiklumas yra vienas nu kito neatskiriami dvyniai.<br>Orizonas Svetas Mardenas",
  "Moralės ir įstatymų pamatas – kad kuo daugiau žmonių patirtų kuo daugiau laimės.<br>Jeremis Benthamas",
  "Kad pasisektų, jūsų sėkmės noras turi būti didesnis, negu jūsų nesėkmės baimė.<br>Bilas Costlis",
  "Sėkmės paslaptis – tai tikslo pastovumas.<br>Bendžaminas Dizraelis",
  "Sėkmė – tai daryti, ką nori, kada nori, kur nori, su kuo nori ir kiek nori.<br>Tonis Robinsas",
  "Tik tie, kurie išdrįsta patirti didelę nesėkmę, gali sulaukti didelės sėkmės.<br>Džonas Kenedis",
  "Sėkmės paslaptis – būti pasiruošus galimybei tada, kai ji ateina.<br>Bendžaminas Dizraelis",
  "Kad būtumėte gyvenime sėkmingi, turite išmokti siekti vieno pagrindinio ilgalaikio savo tikslo ir žongliruoti dviem trim trumpalaikiais arba vidutinės trukmės siekiais vienu metu.<br>Zigas Ziglaras",
  "Išradėjui nepasiseka 999 kartus, kol pagaliau vieną kart pavyksta. Tačiau savo nesėkmes jis traktuoja kaip bandymus.<br>Čarlzas Keteringas",
  "Jei laikysitės disciplinos daryti tai, ką reikia, ir tada, kai reikia, ateis diena, kai galėsite daryti tai, ką norite, ir tada, kai norite.<br>Zigas Ziglaras",
  "Man sėkmė – tai gyventi pagal savo tiesą ir sutarti su pačiu savimi.<br>Robinas Sharma",
  "Nežinau nė vieno tikro kelio į sėkmę, tik vieną – į tikrą nesėkmę: tai noras įtikti visiems.<br>Platonas",
  "Sėkmė yra pasekmė, bet tai neturi būti tikslas.<br>G. Floberas",
  "Bėda neateina viena, bet sėkmė irgi.<br>Romainas Rolandas",
  "Nesėkmė virsta sėkme, jei iš jos pasimokome.<br>Malkombas S. Forbesas",
  "Nesėkmės tai prieskoniai, teikiantys aromato sėkmei.<br>Trumanas Kapotė",
  "Didžiausią malonumą ir atpildą randu darbe, po kurio seka tai, ką pasaulis vadina sėkme.<br>Tomas Edisonas",
  "Mokslas yra besvoris. Brangenybė, kurią jūs visada lengvai nešiojate.<br>Kinų patarlė",
  "Diena be mokslo – tuščiai praleista diena. Tiek daug yra ko mokytis ir tiek mažai turime tam laiko.<br>Albertas Einšteinas",
  "Išauklėti kultūringą žmogų padeda dvi jėgos: menas ir mokslas. Abi šios jėgos susijungia knygose.<br>M. Gorkis",
  "Mokslas neturi tėvynės, bet mokslininkų be Tėvynės nebūna, ir reikšmę, kurią pasaulis teikia mokslininko darbams, jis teikia ir jo Tėvyne.<br>L. Pasteras",
  "Nesvarbu kokia tavo teorija graži, nesvarbu koks protingas tu esi. Jeigu tai nepatvirtinama eksperimentu, tai tuomet ji neteisinga.<br>R. Feidmanas",
  "Hipotezės reikalingos lygiai kaip ir bandymų bei stebėjimų duomenys, kad koks nors mokslas pajudėtų iš vietos ir sparčiau plėtotųsi.<br>J. V. Gėtė",
  "Mokslas nebuvo ir niekuomet nebus užbaigta knyga. Kiekvienas svarbus laimėjimas iškelia naujų klausimų, o visokia raida ilgainiui susiduria su naujais, kaskart didesniais sunkumais.<br>A. Einšteinas",
  "Mokslo teiginius, kalbančius apie tikrovę, visada galima suklastoti. O jeigu to padaryti neįmanoma, vadinasi, jie kalba ne apie tikrovę.<br>Karlas Poperis",
  "Kas turi vaizduotę be mokslo, turi sparnus, bet neturi kojų.<br>Džozefas Jubertas",
  "Mokslas visuomet neteisus. Jis niekuomet neišsprendžia problemos nesukurdamas dar dešimt naujų.<br>B. Šo",
  "Valgymas be malonumo virsta nuobodžia mityba, o mokslas be aistros teršia atmintį. Jis nebepajėgia suvokti to, ką praryja.<br>Leonardas da Vinčis",
  "Knyga – geriausias išmintingo žmogaus draugas.<br>Robinas Sharma",
  "Knygos mus žavi, mums kalba, pataria, jas su mumis sieja kažkoks gyvas ir harmoningas artumas.<br>Frančeskas Petrarka",
  "Knygos – mano ginklas, jomis užkariavau visą pasaulį.<br>Volteras",
  "Išauklėti kultūringą žmogų padeda dvi jėgos: menas ir mokslas. Abi šios jėgos susijungia knygose.<br>Maksimas Gorkis",
  "Geras dalykas kaupti geras knygas, bet kur kas geresnis – dažniau jas skaityti.<br>Frančeskas Petrarka",
  "Knyga, kuri neverta, kad ją skaitytų dukart, neverta ir to, kad ją skaitytų vienąkart.<br>Pjeras Vėberis",
  "Namai, kuriuose nėra knygų, panašūs į kūną be sielos.<br>Ciceronas",
  "Bendravimu su tauriausiais žmonijos protais mes mėgaujamės daugiausia per knygas, ir tas bendravimo būdas prieinamas visiems.<br>Viljamas Eleris Čeningas",
  "Atminkite: jei darote daugiau, nei tai, už ką jums moka, ateis diena, kai jums mokės daugiau už tai, ką darote.<br>Zigas Ziglaras",
  "Darbas – tai svarbiausia gyvenime. Iš visų nemalonumų, iš visų bėdų galima išsivaduoti vien darbu.<br>Ernestas Hemingvėjus",
  "Susitelkite į vieną dalyką, kurį galite atlikti dabar, o ne į visą šimtą, kurį turėsite atlikti ateityje.<br>Ekhartas Tolis",
  "Kas mėgsta savo darbą, nesensta.<br>P. Kasalsis",
  "Rūpinkis tik tuo, ką darai, o ne ką iš to turėsi.<br>B. Gita",
  "Dar niekas be įkvėpimo nėra pasiekęs nieko didingo.<br>R.W. Emersonas",
  "Jeigu mėgsti tai, ką darai, vadinasi, niekada gyvenime nebedirbsi.<br>Konfucijus",
  "Gyvenimo tikslas – išreikšti save.<br>O. Vaildas",
  "Tegul lenktyniauja žirgai, o ne menininkai.<br>B. Bartokas",
  "Taurus žmogus nesišvaisto pažadais, o daro daugiau negu žadėjo.<br>Seneka",
  "Geriau padaryti nedaug, bet gerai, negu daug, bet blogai.<br>Sokratas",
  "Kuo daugiau darote, tuo daugiau galite padaryti.<br>Liucilė Bol",
  "Žmogus, judinantis kalną, pradeda nuo mažų akmenų.<br>Konfucijus",
  "Gerai padaryta yra geriau, negu gerai pasakyta.<br>B. Franklinas",
  "Viskas pigu, ką galima sutvarkyti už pinigus.<br>Erichas Marija Remarkas",
  "Džiaugtis gyvenimu – tai mokytis gauti už savo pinigus ką nors vertinga ir suvokti tai.<br>Ernestas Hemingvėjus",
  "Pinigai, kuriuos turi, – laisvės įrankis; tie, kurių vaikaisi, – vergijos įrankis.<br>Žanas Žakas Ruso",
  "Svarbu ne tai, kiek pinigų uždirbi, o kiek sugebi išlaikyti.<br>Robertas Kijosakis",
  "Už pinigus neįsigysi to, ko reikia sielai.<br>Henris Deividas Toras",
  "Dauguma žmonių saugumą painioja su pinigais.<br>Šakti Gavain",
  "Turtingiausias tas žmogus, kurio džiaugsmams reikia mažiausiai pinigų.<br>Henris Deividas Toras",
  "Pinigai nekuria sėkmės, laisvė tai gali padaryti.<br>Nelsonas Mandela",
  "Gyvenimo tikslas yra tikslingas gyvenimas.<br>R. Šarma",
  "Nesėkmės galimybė neturėtų mūsų atgrasinti nuo teisingo siekio.<br>Abraomas Linkolnas",
  "Užkopus į didžiulį kalną, atrandi dar daugiau kalnų, į kuriuos galėtum įkopti.<br>Nelsonas Mandela",
  "Tvirta, sąmoninga, tikra valia pirmiausia susijusi su įsitikinimu, kad tikslas bus pasiektas.<br>J. V. Gėtė",
  "Tikslo siekimas yra viena svarbiausių sėkmės gyvenime sąlygų, nesvarbu, kokio tikslo yra siekiama.<br>Dž. D. Rokfeleris II",
  "Nežinau nė vieno tikro kelio į sėkmę, tik vieną – į tikrą nesėkmę: tai noras įtikti visiems.<br>Platonas",
  "Nieko didingo nebuvo pasiekta be entuziazmo.<br>Ralfas Voldas Emersonas",
  "Neleisk, kad neįveikiamos užduotys trukdytų atlikti įveikiamas.<br>Janas Vudenas",
  "Mus vilioja aukštuma, bet ne laiptai į ją: žvelgdami į viršūnę mes norėtume eiti į ją lyguma.<br>J. V. Gėtė",
  "Tikslo atkakliai siekiantis žmogus susiranda priemonių, o jei negali jų rasti, sukuria.<br>Viljamas Eleris Čeningas",
  "Savo tikslu pasirinkime aukščiausiąjį gėrį, prie kurio veržtumės, į kurį žvelgtume atlikdami kiekvieną darbą – kaip jūrininkai, nusistatantys kryptį pagal kokią nors žvaigždę. Gyvenimas be tikslo yra klaidžiojimas.<br>Seneka",
  "Kilnūs tikslai, nors ir nepasiekiami, mums brangesni už žemus tikslus, nors ir pasiektus.<br>J. V. Gėtė",
  "Žmogus, jei nežino, ko nori, blaškosi net lygiausiame kelyje, o štai vedamas tikslo jis tvirtai juda pirmyn nekreipdamas dėmesio į sunkumus.<br>Tomas Karlailis",
  "Taurus žmogus nesišvaisto pažadais, o daro daugiau negu žadėjo.<br>Seneka",
  "Idėjos galingesnės už žmogaus fizines jėgas.<br>Sofoklis",
  "Žmonės yra sukurti vieni kitiems.<br>Markas Aurelijus",
  "Kuo žmogus protingesnis ir geresnis, tuo daugiau pastebi gėrio žmonėse.<br>Blezas Paskalis",
  "Spręsti apie žmones reikia ne iš to, ko jie nežino, o iš to, ką ir kaip jie žino.<br>Liukas de Klapje Vovenargas",
  "Daugelis žmonių pervertina tai, ką jie gali pasiekti per metus, tačiau nuvertina, ką gali padaryti per dešimt.<br>Tonis Robinsas",
  "Savo sugebėjimus žmogus gali pažinti tik juos išbandęs.<br>Seneka",
  "Norint būti laimingam su žmonėmis, reikia prašyti jų tik to, ką jie pajėgia.<br>Bernardas Klervietis",
  "Kiekviena aistra yra ir džiuginanti, ir kankinanti.<br>T. Draizeris",
  "Aistra – vienintelis oratorius, kurio argumentai visada įtikina; jų galia tarsi plaukia iš pačios gamtos ir remiasi jos dėsniais. Todėl paprastas, bet aistros pagautas žmogus gali greičiau įtikinti negu iškalbus, tačiau abejingas.<br>Fransua de Larošfuko",
  "Iš pradžių kiekviena aistra silpna, vėliau pati save kursto ir augdama kaupia jėgas. Jos neprisileisti yra lengviau, negu atsikratyti.<br>Seneka",
  "Aistros – tai vėjai, pučiantys į laivo bures. Kai kada jie paskandina jį, bet be jų jis negalėtų plaukti. Viskas pasaulyje pavojinga – ir viskas būtina.<br>Volteras",
  "Didžios aistros tokios pat retos kaip meno šedevrai.<br>O. de Balzakas",
  "Aistros nepaliaujamai smerkiamos, joms priskiriamos visos žmonių nelaimės ir pamirštama, kad jos yra ir visų mūsų džiaugsmų šaltinis.<br>D. Didro",
  "Menas yra jausmo įkūnijimas.<br>Hermanas Melvilė<br>Jausmas – ugnis, o mintis – alyva.<br>Visarionas Belinskis",
  "Mūsų slepiami jausmai yra daug galingesni už atvirai reiškiamus.<br>O. de Balzakas",
  "Ne idėja, o jausmu patraukiami žmonės.<br>Hipolitas Tenas Taine",
  "Jausmai geri tuo, kad nuveda mus klystkeliais, o mokslas – kad nieko bendra su jausmais neturi.<br>O. Vaildas",
  "Žmogus, kurio jausmai truputį nublanko, labiau stengiasi patikti negu mylėti.<br>Žoržas Sandas",
  "Tik tie jausmai šventi, kurie perėjo metų, išbandymų žaizdrą ir nesibaigia dėl geografijos ar metų laikų.<br>Aleksandras Gercenas",
  "Galimybės neatsiranda iš niekur – jas reikia susikurti ir užsidirbti. Tai reikalauja atkaklumo ir drąsos.<br>Indira Gandhi",
  "Kiekviena diena kupina pamokų ir mokymų, t.y paslėptų dovanų.<br>Šakti Gavain",
  "Tik didelė idėja gimdo didelę energiją.<br>G. Medinskis",
  "Sunkūs uždaviniai kaip tik todėl ir yra nepaprastai malonūs, kad juos spręsdamas išmoksti visapusiškai suvokti save.<br>L. Metsaris",
  "Rūpinkis tik tuo, ką darai, o ne ką iš to turėsi.<br>B. Gita",
  "Kiekvienam įkvėpimo lašui reikia dar pridėti devyniasdešimt devynis prakaito lašus.<br>M. Larnis",
  "Vienintelė kliūtis mūsų rytdienos planus įgyvendinti gali būti šiandienės mūsų abejonės.<br>Teodoras Ruzveltas",
  "Nėra nieko, ko pasistengęs negalėtum įveikti. Svarbiausia turėti valios ir niekada nepasiduoti.<br>Robertas Korbetas",
  "To, kas mums atrodo neįmanoma, galbūt paprasčiausia nesistengėte padaryti.<br>Johanas Volfgangas Gėtė",
  "Sunkumuose visada slypi galimybės.<br>Albertas Einšteinas",
  "Vengdami problemų niekada nebūsite tas, kuris jas įveikė.<br>Ričardas Bachas",
  "Muzika ir ritmas randa kelią į slapčiausią vietą žmogaus sieloje.<br>Peteras Hoegas",
  "Muzika privalo išskelti ugnį iš žmogaus sielos.<br>L. van Bethovenas",
  "Muzika – tai didžiausias gėris, kurį pažįsta mirtingieji.<br>D. Adisonas",
  "Muzika negali mąstyti, bet ji gali įkūnyti mintį.<br>R.Vagneris",
  "Karas vienodai apmokestina visus: iš vyrų paima kraują, iš moterų ašaras.<br>Viljamas Tekerėjus",
  "Kovos su blogiu priemonės kartais blogesnės už patį blogį.<br>Publijus Siras",
  "Karas – tai blogis, darantis gėdą žmonių giminei.<br>Fransua Fenelonas",
  "Tik ligoninėje galima pamatyti, kas yra karas.<br>Erichas Marija Remarkas",
  "Pergalę, pasiektą mūšyje, derėtų švęsti pagal gedulo apeigas.<br>Lao Dzė",
  "Žmonėms, nesiklausantiems patarimų, neįmanoma padėti.<br>B.Franklinas",
  "Žmonių santykiai būtų daug geresni, jei žmonėms būtų taip pat lengva tylėti kaip ir kalbėti.<br>B. Spinoza",
  "Žmonių išmintingumas proporcingas ne jų patirčiai, o sugebėjimui jos įgyti.<br>Džordžas Bernardas Šavas",
  "Žmogus, kuris galvoja tik apie save ir visur ieško naudos, negali būti laimingas. Nori gyventi sau, gyvenk kitiems.<br>Seneka",
  "Žmogus pailsi nuo vieno darbo tik tada, kai pradeda kitą<br>A. Fransas",
  "Žmogus negali nuskriausti kito žmogaus – jis gali nusiskriausti tik pats.<br>Dž. Londonas",
  "Žmogus negali griauti to, ko pats negali sukurti.<br>R.Tagorė",
  "Žmogus atsiskleidžia galinėdamasis su kliūtimis.<br>A. de Sent-Egziuperi",
  "Mūsų poelgiai ne tokie geri ir ne tokie nuodėmingi kaip mūsų norai.<br>L. de Vovenargas Ziuperi",
  "Žmogus – vien santykių mazgas. Ir tik santykiai turi žmogui reikšmės.<br>A. de Sent Egziuperi",
  "Žmoguje viskas turi būti gražu: ir veidas, ir drabužiai, ir siela, ir mintys.<br>Čechovas",
  "Žmogui reikia tikslo – ir jis veikiau norės nieko, nei išvis atsisakys norėti.<br>F.Nyčė",
  "Žmogui neskirta suprasti, jeigu jis nejaučia meilės, ir neleista pažinti, jei jis nesiaukoja.<br>A.R.Lenormanas",
  "Žmogaus teisių deklaracijoje liko užmirštos dvi teisės: teisė sau prieštarauti ir teisė pasišalinti.<br>Bodleras",
  "Žmogaus protas turi tris visrakčius: žinias, mintis ir vaizduotę.<br>V.Hugo",
  "Žmogaus prigimtis liepia alkaniems kovoti dėl maisto, išsekusiems stengtis pailsėti, darbo išvargintiems ieškoti atokvėpio, o pažemintiems rūpintis pagarba.<br>Kung Sun Jangas",
  "Žmogaus aistros nuolat budrauja tykodamos sau grobio, o protas miega, kol pažadinamas. J.G.Herderis",
  "Žinoti tai, ką žino visi, vadinasi, nieko nežinoti, Žinojimas prasideda nuo to, ko žmonės nežino.<br>R. de Gurmonas",
  "Įžymybė yra asmuo, kuris visą gyvenimą sunkiai dirba, kad taptų įžymus, o paskui dėvi juodus akinius, kad niekas jo nepažintų.<br>Fredas Alenas",
  "Įžvalgumas nerodo proto. Kvailiai ir net bepročiai būna stebėtinai įžvalgūs.<br>A.Puškinas",
  "Įsišaknijusios silpnybės panašios į musę: tu šimtus kartų ją nuvarai, o ji grįžta ir kankina tave vis labiau.<br>L.Šeferis",
  "Įrankiai ir jų naudojimosi būdai kinta, o gamta ir jos reiškiniai visados vienodi.<br>Vang Čungas",
  "Yra žmonių, manančių, kad visa, kas daroma rimtu veidu, yra protinga<br>G.K.Lichtenbergas",
  "Yra žmonių, kurie niekada neklysta todėl, kad jų niekada nevargina jokios protingos mintys<br>J.V.Getė",
  "Visų sunkiausia – pažinti save, visų lengviausia – patarinėti kitiems.<br>Talis",
  "Visus didžiausius atradimus padarė tie žmonės, kurių jausmai pranoko mintis.<br>Č.H.Parkcherstas",
  "Visuomet atsilieka tas, kuris nedrįsta aplenkti.<br>M.E.Kvintilianas",
  "Visos moterys vienodos, tik kai kurios neišsiduoda.<br>Visos moterys klaidina vyrus neišbrendamam rūke.<br>M. Cvetajeva",
  "Viską, ką darai, reikia daryti gerai, net jei darai beprotybę.<br>H. de Balzakas",
  "Visi žmonės eina tais pačiais gyvenimo keliais, bet ne visi vienodai įmina pėdas.<br>Hugo",
  "Visi skundžiasi savo atmintimi, bet niekas nesiskundžia savo protu.<br>F. de Larošfuko",
  "Visi apibendrinimai yra pavojingi. Šitas – taip pat.<br>Alexandras Dumas",
  "Visada būk savo valios šeimininkas ir savo sąžinės vergas.<br>M. Ebneras- Ešenbachas",
  "Visa problema su pasauliu yra ta, kad kvailiai ir fanatikai visada tokie savimi pasitikintys, o išmintingesni – tokie pilni dvejonių<br>Bertrandas Ruselis",
  "Viltis – tai lankai, kurie neleidžia plyšti širdžiai.<br>T.Fuleris",
  "Viltis – geri pusryčiai, bet bloga vakarienė.<br>F.Bekonas",
  "Vienintelis būdas atsikratyti pagundos – jai atsiduoti.<br>Oskaras Vaildas",
  "Vieni žmonės garsūs, kiti verti tokie būti.<br>Lesingas",
  "Vieni esame lyg rašalas. Kiti – lyg popierius. Ir jei ne vienų juodumas, kiti būtume nebyliai. Ir jei ne vienų baltumas, kiti būtume akli.<br>K.Džibranas",
  "Vienas dalykas – meluoti, kitas – kalbomis, žodžiais nutolti nuo tiesos klystant, o ne iš piktos valios.<br>P.Alberas",
  "Viena mirtis – tai tragedija, milijonas mirčių – tai statistika.<br>Josefas Stalinas",
  "Viena diena rūpesčių labiau išsekina negu savaitė sunkaus darbo.<br>D. Emersonas",
  "Verčiau būsiu ryškiausiu meteoru negu amžina, bet susnūdusia planeta…<br>Dž. Londonas",
  "Valia gali pakeisti net mūsų delnų linijas.<br>Ž.Kokto",
  "Valgymas be malonumo virsta nuobodžia mityba, o mokslas be aistros teršia atmintį. Ji nebepajėgia suvokti to, ką praryja.<br>Leonardas da Vinčis",
  "Valdžia nieko negadina. Gadina baimė… baimė prarasti valdžią.<br>Džonas Steinbeckas",
  "Valdžia nieko negadina. Gadina baimė… baimė prarasti valdžią<br>Džonas Steinbeckas",
  "Vaizduotė – tai ginklas kare su realybe.<br>Julesis de Gaultieris",
  "Užpjudytas ir priremtas prie sienos katinas virsta tigru.<br>M. de Servantesas",
  "Už viską pasaulyje tenka mokėti, bet visada patartina derėtis.<br>A. Parkinsonas",
  "Už kvailus norus kartais žiauriai baudžiama jų išsipildymu.<br>I. Kurcas",
  "Tėvas dabartinėje miestiečių šeimoje užima labai mažai vietos. Nebent jis žaidžia golfą.<br>Bertrandas Ruselas",
  "Tėra du tikrai begaliniai dalykai: visata ir kvailystė. Ir aš nesu tikras dėl visatos.<br>Albertas Einšteinas",
  "Tylėjimas – vienas iš sunkiausiai paneigiamų argumentų.<br>H.V.Šo",
  "Tylėjimas – paprastos sielos, patyrusios visą žmogiško sielvarto nykumą, prieglauda.<br>V.Hugo",
  "Trečią valandą visada per vėlu arba per anksti ką nors daryti.<br>Žanas Pauislas Sartras",
  "Tingumas – tai nieko daugiau negu ilsėjimasis prieš nuovargį.<br>Raimondas Chandleris",
  "Tik tas nekrinta, kuris niekada nekopė.<br>Dž.Hauelsas",
  "Tik pasiekę tikslą sužinome, kad kelias buvo tinkamas.<br>P.Valeri",
  "Tik kvailiai ir numirėliai niekada nekeiĿia nuomonės.<br>Dž.R.Lovelis",
  "Tiesą sakant, tik nedaugelis gyvena šiandien. Dauguma rengiasi gyventi vėliau.<br>Dž. Sviftas",
  "Tiesa yra bjauri. Mes turime meną tam, kad mūsų nepražudytų tiesa.<br>F. Nyčė",
  "Tiesa kartais linksta, bet nelūžta ir išplaukia virš melo kaip riebalai virš vandens.<br>M. de Servantesas",
  "Tie, kuriuos mes mylime, brangūs mums ne savo stiprybe, o silpnumu.<br>S. Moemas",
  "Tie, kurie nereikalauja, ir patys nieko neduoda.<br>P.Gilė",
  "Tie, kurie giria moteris, pažįsta jas nepakankamai, o tie, kurie bara, nepažįsta apskritai.<br>G. Pigo-Lebrenas",
  "Tetyli tas, kuris davė, tekalba tas, kuris gavo.<br>Cervantesas",
  "Ten, kur visi kuproti, nuostabi figūra tampa bjauri.<br>H.de Balzakas",
  "Televizija įrodė, kad žmonės mieliau žiūrės į bet ką, negu vienas į kitą.<br>Anna Landers",
  "Tas, kuris viską palieka atsitiktinumo valiai, paverĿia savo gyvenimą loterija.<br>T.Fuleris",
  "Tas, kuris toks kurčias, kad net iš draugo nenori išgirsti tiesos, yra beviltiškas.<br>Ciceronas",
  "Tas, kuris sugeba valdyti moterį, sugebės valdyti valstybę.<br>H. de Balzakas",
  "Tas, kuris nori, daro daugiau negu tas, kuris gali.<br>G.Merjė",
  "Tas, kuris nieko neklausia, nieko neišmoks.<br>T.Fuleris",
  "Tas, kuris nemyli savo šalies, nemyli nieko.<br>Dž.N.Baironas",
  "Tas, kuris myli, gyvena, o kuris gyvena, dirba.<br>V. van Gogas",
  "Tas didžiausias žmogaus draugas ir pats didžiausias priešas – tai jo vaizduotė.<br>A.Grafas",
  "Tarp gardžių pietų ir gyvenimo yra tik vienas skirtumas: tai, kas saldu, valgoma pietų pabaigoje.<br>R. Stivensonas",
  "Tam, kad ką nors išrastum, reikia geros vaizduotės ir daugybės nereikalingų daiktų.<br>Thomas Alva Edisonas",
  "Taktiškimas – tai sugebėjimas apibūdinti kitus taip, kaip jie mato patys save.<br>Abrahamas Lincolnas",
  "Tai, už ką žmonės miršta, nebūtinai būna tiesa.<br>O. Vaildas",
  "Tai, ką vadiname kitų nuomone, savo laikome – eskperimentu.<br>R.V.Emersonas",
  "Tai, kas eina iš širdies, širdį ir pasiekia.<br>Dž. Dž. Pajetas",
  "Sąžinė liguistai jautri. Sąžine galima naudotis, bet, panašiai kaip fantazijos ir skrandžio, jos negalima perkrauti.<br>R.L.Stivensonas",
  "Svetimos ydos visada mums prieš akis, o savo – už nugaros.<br>Seneka",
  "Svarbiausia yra pripažinti grožį ir neprarasti sugebėjimo žavėtis. Pamatęs groži tuose dalykuose, kurių nekenti, gali juos nugalėti.<br>Michaelas Larsenas",
  "Svarbiausia turėti faktų. O paskui juos galite iškraipyti, kaip norite.<br>Markas Tvainas",
  "Svarbiau yra apgalvotai veikti negu protingai mąstyti.<br>Ciceronas",
  "Supratimas yra patirties išdava, idėja – jos vaisius: pirmajam reikia proto, antrajam – išminties.<br>J.V.Gėtė",
  "Su neteisybe arba bendradarbiaujama, arba kovojama.<br>A. Kamiu",
  "Stenkis turėti tai kas tau miela, nes kitaip būsi priverstas pamilti tai ką turi.<br>Bernardas Šo",
  "Stenkis išmokti ką nors apie viską ir viską apie ką nors.<br>Thomas H. Huksleris",
  "Stebuklas visada yra kažkur šalia nevilties.<br>E.M. Remarkas",
  "Skirtumas tarp genialumo ir kvailystės yra tas, kad genialumas – ribotas<br>Anonimas",
  "Senatvėje labiau sugebame nelaimių išvengti, jaunystėje – jas iškęsti.<br>A. Šopenhaueris",
  "Savo sumanymais žmogus visada didis.<br>Remarkas",
  "Savi įsitikinimai nekabinami ant sienos.<br>H.Balzakas",
  "Rūkymas yra pagrindinė statistikos priežastis.<br>Fletčeris Knebelas",
  "Reikia būti optimistu darbo pradžioje ir smarkiai abejoti pabaigoje.<br>L.Hiršfeldas",
  "Realybė yra tai, kas nuo tavęs neatstoja netgi tada, kai tu ja nustoji tikėti.<br>Filipas K. Dickas",
  "Racionalus žmogus pats adaptuojasi prie savo aplinkos. Neracionalus gi atkakliai bando paĿią aplinką pritaikyti prie savęs. Kaip tik todėl visas progresas ir priklauso nuo neracionaliųjų.<br>Bernardas Šou",
  "Pyktis neapakina: jis gimsta iš aklumo.<br>A. de Sent-Egziuperi",
  "Protingai kalbėti sunku, o protingai tylėti dar sunkiau.<br>K. N. Bouvis",
  "Prognozės ne visada pildosi. Išimtį sudaro tie atvejai, kai protingi pranašai būna įsitikinę dabarties įvykiais iki juos paskelbdami.<br>G.Fereras",
  "Privilegija visur būti kaip namie priklauso tik karaliams, mergšėms ir vagims.<br>H. de Balzakas",
  "Prieš rodydamas mano dėmes, nusiplauk pirštą.<br>B.Franklinas",
  "Prastai išauklėto žmogaus drąsa virsta šiurkštumu, mokytumas – pedantiškumu, sąmojingumas – juokdaryste, paprastumas – nekultūringumu, geranoriškumas – meilikavimu.<br>Dž. Lokas",
  "Praeitį lengviau neigti nei taisyti.<br>Livijus",
  "Praeitis ir dabartis – mūsų priemonės, tik ateitis – mūsų tikslas.<br>B.Paskalis",
  "Pomėgis kolekcionuoti – pirmoji proto sutrikimo pakopa.<br>H.Balzakas",
  "Politika yra menas ieškoti problemų, rasti jų, nepriklausomai nuo to ar jų yra, ar ne, diagnozuoti jas neteisingai ir skirti ne tuos vaistus.<br>Ernestas Benas",
  "Politika panaši į sfinksą iš pasakos: praryja visus, kurie nepajėgia įminti jos mįslių.<br>A. de Rivarolis",
  "Polinkis bendrauti yra maždaug priešingai proporcingas intelekto vertei.<br>A.Šopenhaueris",
  "Plepumas – žmogaus amžių išduodanti liga.<br>D. Benas",
  "Pirma taurė priklauso troškuliui, antra – linksmumui, treĿia – malonumui, ketvirta – beprotybei.<br>A.Skitas",
  "Pinigai ne visada atneša laimę. Žmonės su 10 milijonų dolerių nėra laimingesni už žmones su 9 milijonais dolerių.<br>Hobartas Braunas",
  "Pinigai – karo varomoji jėga.<br>Ciceronas",
  "Pikti žmonės neturi dainų.<br>J.G.Zoimė",
  "Pesimistas mato sunkumų kiekvienoje galimybėje, optimistas bet kokiame sunkume įžiūri galimybę.<br>Vinstonas Čerčilis",
  "Pesimistas – tai toks žmogus, kuris iš dviejų blogybių pasirenka abi.<br>Oskaras Vaildas",
  "Pavydus žmogus suteikia sau nemalonumų tarsi priešui.<br>Demokritas",
  "Pavyduoliai amžinai žvelgia pro žiūronus, kurie mažus daiktus paverčia dideliais, nykštukus – milžinais, spėliones – tiesa.<br>M.Servantesas",
  "Pats didžiausias malonumas – padaryti tai, ko, kitų nuomone, jūs padaryti negalite.<br>K.Chabardas",
  "Patriotizmas – tai įsitikinimas, kad ši šalis yra tobuliausia iš visų todėl, kad jūs joje gimėte.<br>Džordžas Bernardas Šavas",
  "Patirtis yra žiaurus mokytojas, nes pirmiausia pasiunčia išbandymą, o tik po to – pamoką.<br>Vernonas Lavas",
  "Patirtis yra mūsų nusivylimų visuma.<br>P. Ogė",
  "Patirtis didina mūsų išmintį, bet nemažina mūsų kvailumo.<br>H. V. Šo",
  "Pastatyti paminklą kam nors gyvam, vadinasi, iš anksto pripažinti, kad ainiai to nepadarys.<br>A.Šopenhaueris",
  "Pasiūlos ir paklausos požiūriu, gyvybė yra pigiausas dalykas pasaulyje. Vandens, žemės, oro kiekis apibrežtas, bet gyvybė gimdanti gyvybę – begalinė.<br>Dž.Londonas",
  "Pasitaiko žmonių, kuriems lotynų kalbos mokėjimas netrukdo būti asilais.<br>M.Servantesas",
  "Pasaulis juokingas – tu gali pavirsti į archangelą, kvailį ar nusikaltėlį – niekas nepamatys! Bet jei tau trūksta sagos, tai pamato kiekvienas.<br>E.M.Remarkas",
  "Pasaulis – tai veidrodis, ir jis grąžina kiekvienam jo paties atvaizdą.<br>V.M.Tekerėjus",
  "Paprastai viltis – blogas vedlys, nors geras pakeleivis.<br>Dž. S. Halifaksas",
  "Pamišę individai – tai labai retas reiškinys, o štai pamišusios grupės, partijos, tautos, epochos – tai tiesiog taisyklė.<br>Fridrichas Nyčė",
  "Pamilkite tuos, kurių kitokie įsitikinimai, ir pamatysite, kaip išlošite.<br>N.Gogolis",
  "Pagrindinė priežastis, kodėl yra tiek nedaug politikių moterų, yra ta, kad pasidažyti du veidus užima labai daug laiko.<br>Maurenas Miurfis",
  "Pagrindinis gyvenimo tikslas – įveikti senėjimą.<br>Dikas Vertimeris",
  "Pagalvok bent kartą prieš duodamas, dukart prieš imdamas ir tūkstantį kartų prieš reikalaudamas.<br>M.Ebneris-Ešenbachas",
  "Padegti namą, kad išsikeptum kiaušinienės, – egoisto savybė.<br>F.Bekonas",
  "Organizuotas nusikalstamumas Amerikoje valdo daugiau kaip 40 milijardų dolerių. Ir labai mažai teišleidžia kanceliarinėms prekėms.<br>Vudis Alenas",
  "Optimistas sako, kad mes gyvename geriausiame iš visų pasaulių; pesimistas bijo, kad tai tiesa.<br>B.Keibelas",
  "Optimistas plyšauja, kad mes gyvename pačiame geriausiame pasaulyje, pesimistas nuogąstauja, kad būtent taip ir yra.<br>Rėjus Bredberis",
  "Nėra žmogaus, kuris, gilindamasis į save, sulauktų linksmų rezultatų.<br>M. K. Čiurlionis",
  "Nėra žmogaus, kuriam gyvenimo loterijoje tektų tik laimėjimai.<br>B.Prusas",
  "Nėra tokio skausmo, kurio negalima būtų išverkti.<br>N.Gogolis",
  "Nėra tokio pirmadienio, kuris neužleistų vietos antradieniui.<br>A. Čechovas",
  "Nėra jokios kitos nuodėmės, kurią taip lengva širdim ir dažnai darytų šiaip jau dori žmonės, kaip savo valdžios apgaudinėjimas.<br>Bendžaminas Franklinas",
  "Nė vienas iš žmogiškų dalykų nėra vertas, kad dėl jo labai sielvartautum.<br>Platonas",
  "Nė vienas gydytojas nežino geresnio už viltį vaisto pavargusiam kūnui ir sielai.<br>S.Cveigas",
  "Nusiminimas galiausiai tampa įpročiu, beje, netikusiu.<br>A. de Monterlanas",
  "Nuostabiausios savybės: tesėti pažadą, nevėluoti į sutartą susitikimą ir laiku atsisveikinti.<br>A.Klintsas",
  "Nuomonė apie žmogų, kaip ir apie beveik kiekvieną būtybę, priklauso nuo to, iš kokio atstumo į jį žiūri.<br>B.Džonsonas",
  "Nuo depresijos geriausiai gydo kilnūs veiksmai ir karšta vonia.<br>Dudis Smitas",
  "Nors žmogaus gyvenimas neįkainojamas, mes visad elgiamės taip, tarsi egzistuotų kažkas dar vertingesnio.<br>A. de Sent-Egziuperi",
  "Nori gauti protingą atsakymą, klausk protingai.<br>J.V. Gėtė",
  "Norai būtini tam, kad gyvenimas nesustotų.<br>S.Džonsonas",
  "Nieko neveikti – pasibaisėtinai sunkus darbas.<br>O.Vaildas",
  "Niekas žmogaus taip nestabdo kaip jis pats save.<br>A.Belas",
  "Niekas savaime nėra nei gražu, nei bjauru, bet gražu, jei daroma gražiai, ir bjauru – jei bjauriai.<br>Platonas",
  "Niekada neteikite neprašytų paslaugų.<br>H.Balzakas",
  "Niekada nestovėjau, kai galėjau sėdėti, ir niekada nesėdėjau, kai galėjau gulėti.<br>V.Čerčilis",
  "Nežinojimas – tarytum trapus, egzotiškas augalas: tik paliesk jį, ir žiedas nukris.<br>O.Vaildas",
  "Nežinau didesnio pasiaukojimo negu paduoti ranką žmogui, kuris visiškai neteko vilties.<br>N.Gogolis",
  "Neįmanoma būna tol, kol pasidaro įmanoma.<br>Žanas-Lukas Pikardas",
  "Neterškite meilės draugyste. Pabaiga yra pabaiga.<br>M. Remarkas",
  "Nesėkmė – ne nusikaltimas; nusikalstama kelti sau tikslus, neatitinkanĿius galimybių.<br>Dž.R.Lovelis",
  "Nerimas – tai nepasitenkinimas, o nepasitenkinimas – svarbiausia pažangos sąlyga.<br>Tomas Edisonas",
  "Neretai optimizmas tėra dar viena minties tingumo apraiška.<br>E.Erio",
  "Nereikia sakyti visko, ką žinai, bet visada reikia žinoti, ką sakai.<br>M.Klaudijus",
  "Neplūskite orų – devynios dešimtosios žmonijos nesugebėtų pradėti jokio pokalbio, jeigu orai nebjurtų.<br>K. Chabardas",
  "Nepatikti blogiems – girtinas dalykas.<br>Seneka",
  "Nepakanka nekenkti – reikia padėti savo broliams.<br>Dž.Madzinis",
  "Nelėtink žingsnių, neskink gėlių, norėdamas jas išsaugoti, eik tik pirmyn – gėlės žydės visam tavo kely.<br>R.Tagorė",
  "Nelaimė visada atskrenda ant sparnų, o išeina klibikšĿiuodama.<br>Volteras",
  "Nekompetentingas advokatas gali užtęsti teismo procesą mėnesius ar net metus, o kompetentingas – dar ilgiau.<br>Evele J. Joungeris",
  "Negalima paspausti rankos sugniaužus kumštį.<br>Indira Gandhi",
  "Nebūtina daryti žygdarbių, visai pakanka mažų dalykėlių, atliktų su didele meile.<br>Motina Teresė",
  "Mūsų slepiami jausmai yra daug galingesni už atvirai reiškiamus.<br>O. Balzakas",
  "Mūsų progresas vertinamas ne pagal tų, kurie turi daug, pertekliaus didėjimą, o pagal tai, ar mes sugebame pakankamai aprūpinti tuos, kurie turi per mažai.<br>T.Ruzveltas",
  "Mūsų nelaimė ta, kad užuot matę dabartį, mes žiūrime į ateitį.<br>N. Gogolis",
  "Mūsų mokslinės galios pralenkė dvasines jėgas. Mes taikliai valdėme raketas, bet visai į šalį nuvairavome žmogų.<br>Martinas Lutheris Kingas Jr.",
  "Mylėti – tai žiūrėti ne vienas kitam į akis, o abiem viena kryptimi.<br>A. de Sent Egziuperi",
  "Muzika su pietumis – tai įžeidimas ir virėjui, ir smuikininkui.<br>G. K. Chestertonas",
  "Mums atrodo, jog žmonės blogai suvokia savo galimybes ir savo jėgas: pirmąsias jie pervertina, antrąsias – sumenkina.<br>F.Bekonas",
  "Moterį reikia mylėti ir nesistengti ją suprasti.<br>O.Vaildas",
  "Mesti rūkyti – lengviausias dalykas; kaip aš galiu to nežinoti – juk meĿiau jau tūkstantį kartų.<br>M.Tvainas",
  "Mes priversti tikėti likimu. Nes kaipgi kitaip galėsime paaiškinti sėkmę tų, kurių nemėgstame.<br>Žanas Kokteau",
  "Menkas liūdesys šnekus, didis sielvartas bežadis.<br>Vergilijus",
  "Menininko nelaimė ta, kad jis nei visiškai vienuolis, nei visiškai pasaulietis ir yra kankinamas abiejų rūšių pagundų.<br>Liuisas Guilouksas",
  "Meilė – tai ne žiūrėjimas vienas į kitą, tai žiūrėjimas kartu ta paĿia kryptimi.<br>A. de Sent-Egziuperi",
  "Maža tėra dalykų, kuriuos būtų sunkiau ištverti už įkyrias nuorodas į gerus pavyzdžius.<br>Markas Tvainas",
  "Mandagumas – tai nerašytas susitarimas ignoruoti vienas kito dorovės ir intelekto skurdą ir jo nepabrėžti.<br>A. Šopenhaueris",
  "Liūdesys – pats beprasmiškiausias iš visų žmogaus išgyvenimų.<br>Dž. Leopardis",
  "Lengva paslėpti neapykantą, sunkiau meilę, bet sunkiausia – abejingumą.<br>L.Berne",
  "Laukinis tigras, kuris abejoja, neprilygsta įgelti pasiryžusiai širšei.<br>Si-Ma Cjenas",
  "Laisvė yra teisė daryti viską, kas nekenkia kitiems.<br>M.Klaudijus",
  "Laisvė reiškia atsakomybę. Štai kodėl dažnas jos bijo.<br>Dž.B.Šo",
  "Laisvė – stiprus vynas, trikdanatis silpnas smegenis; tik ilgai pratinantis galima palengva priprasti prie stiprių jos dozių.<br>Ž.Š. de Sismondis",
  "Laimė yra santykinė kaip virimo temperatūra.<br>Vu Džing Sjungas",
  "Laimė nėra kažkas ką tu patiri, tai kažkas, ką tu prisimeni.<br>Oskaras Levantas",
  "Laimė – trumpa stotelė tarp “per mažai” ir “per daug”.<br>M. Heidegeris",
  "Laimė – tai mūsų sugebėjimų panaudojimas kasdieniniame gyvenime.<br>Balzakas",
  "Laikas – nuostabus mokytojas, deja, užmušantis savo mokinius.<br>H. Berliozas",
  "Labdaros principas: kažkas daro kažką kitam, kol kažkas žiūri.<br>Bernardas Šou",
  "Ką nors padaryti reikia ne taip jau daug pastangų; o štai nuspręsti, kas darytina, reikia iš tikro didžių pastangų.<br>K. Chabardas",
  "Kvailys, pripažinęs, kad yra kvailys, jau nebe kvailys.<br>F. Dostojevskis",
  "Kvailiui senatvė – našta, neišmanėliui – žiema, o mokslo vyrui – auksinė pjūtis.<br>Volteras",
  "Kvailio liežuvis aplenkia mintį.<br>Isokratas",
  "Kvailiai nelaistomi, jie auga patys.<br>T.Fuleris",
  "Kuo žmogus protingesnis, tuo daugiau pastebi žmonėse gero.<br>B.Paskalis",
  "Kuo žmogus mažiau apie save galvoja, tuo vertesnis.<br>E.M.Remarkas",
  "Kuo ledas plonesnis, tuo labiau norisi sužinoti, ar išlaikys.<br>H.V.Šo",
  "Kompiuteriai yra visiškai nenaudingi. Jie tegali jums duoti tik atsakymus.<br>Pablas Pikaso",
  "Koks skurdžius tas, kuris neturi nieko, išskyrus pinigus.<br>A.Grafas",
  "Koks baisus gali būti protas, jeigu jis netarnauja žmogui.<br>Sofoklis",
  "Kojomis žmogus turi įaugti į savo tėvynės žemę, bet jo akys teaprėpia visą pasaulį.<br>Dž.Santajana",
  "Knygos – minties laivai, plaukiojantys laiko bangomis ir rūpestingai gabenantys savo brangų krovinį iš kartos į kartą.<br>F.Bekonas",
  "Klaidos priežastis – geresnio varianto nežinojimas.<br>Demokritas",
  "Kitų ydos, iš kurių mes juokiamės, mumyse juokiasi iš mūsų.<br>Č.F.Braunas",
  "Kitaip sudėlioti žodžiai turi kitokią prasmę, o kitaip sudėliotos prasmės – kitokį poveikį.<br>Blezas Paskalis",
  "Kiekvienas žmogus turi tris jaunystes: kūno, širdies ir proto. Nelaimei, jos niekad nesutampa.<br>F. Fenelonas",
  "Kiekvienas žmogus turi tris charakterius: tą, kuris jam priskiriamas, tą, kurį jis pats sau priskiria, ir pagaliau išties esamą.<br>V.Hugo",
  "Kiekvienas žmogus gali pergyventi pasaulio pabaigą. Tatai vadinama nusivylimu.<br>V.Hugo",
  "Kiekvienas gieda savo giesmę, tikėdamas, kad tai nuostabiausia, pasauliui dar negirdėta giesmė.<br>K.Makalou",
  "Kiekvienas bandymas dreskia dviem nagais – viltimi ir smalsumu.<br>H.Balzakas",
  "Kiekvienam pagal poreikius, iš kiekvieno – pagal galimybes.<br>E.Kabė",
  "Kiekviena diena yra vakarykštės mokinė.<br>Publilijus Siras",
  "Keliauti, vadinasi, kas minutę gimti ir mirti.<br>V.Hugo",
  "Keliais žodžiais galėĿiau apibrėžti viską, ką išmokau iš gyvenimo. Jis tęsiasi.<br>Robertas Frostas",
  "Keliai, kurie neveda niekur, nuveda toliausiai.<br>Ž.Volfromas",
  "Kaulas, numestas šuniui, nėra gailestingumas; gailestingumas – tai kaulas, kuriuo dalijiesi su šunimi, kai esi alkanas ne mažiau už jį.<br>Dž.Londonas",
  "Kas žengia švelniai – eina toli.<br>Kinų išmintis",
  "Kas yra žmogus gamtoje? Niekas prieš begalybę, viskas prieš nieką, centras tarp visko ir nieko.<br>B.Paskalis",
  "Kas daug atsisako, gali daug ką sau leisti.<br>Ž.Šardonas",
  "Karštas arklys kartu su raiteliu gali nusisukti sprandą kaip tik tame takelyje, kuriuo atsargus asilas žingsniuoja neklupdamas.<br>G.E.Lesingas",
  "Kartą gyvenimą Fortūna beldžiasi į kiekvieno žmogaus duris, bet žmogus dažniausiai tuo metu sėdi kaimyninėje smuklėje ir negirdi jos beldimo.<br>M.Tvainas",
  "Karts nuo karto žmogus atsitiktinai užkliūna už tiesos, bet dažniausiai jis atsikelia ir nužingsniuoja toliau.<br>Vinstonas Čerčilis",
  "Kartais paprieštarauti reiškia pasibelsti į duria, kad sužinotum, ar yra kas namie.<br>D. de Žirardenas",
  "Kantrybė yra geriausias vaistas nuo įvairiausių kančių.<br>Plautas",
  "Kaltas ne tas, kuris nusideda, o tas, kuris nedavė nusidėjusiam šviesos.<br>V.Hugo",
  "Kaip žinia, visų vaidų ypatybė – abiejų pusių silpnumas.<br>Volteras",
  "Kaip turi būti sunku gyventi vien tuo, ką žinai ir ką atmeni, neturint ko tikėtis.<br>A.Kamiu",
  "Kaip meilė gyvenimui iš esmės yra tik mirties baimė, taip žmonių siekimas bendrauti iš tikrųjų nėra tiesioginė reikmė: jos pagrindą sudaro ne meilė draugijai, o vienatvės baimė.<br>A. Šopenhaueris",
  "Kaip galima valdyti šalį, kuri turi 246 rūšių sūrių.<br>Čarlis DeGauleris",
  "Kai žmogus nežino, į kurį uostą plaukti, joks vėjas nebus palankus.<br>Seneka",
  "Kai visko netenkama, vis dėlto dar lieka ateitis.<br>K.N.Bouvis",
  "Kai prarandi, tampi kitoks. Kai prarandi, norisi išsaugoti. Kad galėtum eiti į priekį, turi atsigręžti atgal.<br>Michaelas Larsenas",
  "Kai kurie žmonės padaro daug pikta vien dėl savo poreikio paplepėti.<br>V.Hugo",
  "Kai iš pašaukimo ar pagal profesiją esi daug mąstęs apie žmones, kartais imi ilgėtis primatų. Jie bent neturi slaptų minčių.<br>A.Kamiu",
  "Kai gamta palieka kam nors proto spragą, paprastai užtepa ją storu pasitenkinimo savimi sluoksniu.<br>H.V.Longfelas",
  "Kai esi mylimas, neabejoji niekuo. Kai myli pats, abejoji viskuo.<br>S. G. Koletas",
  "Kadangi negalite padaryti visko, ko norite, tai norėkite tik to, ką galite padaryti.<br>Terencijus",
  "Kad turėtumėte teisę žmones smerkti, o paskui, pirmiausia turime mylėti žmoniją.<br>Š.P.Diuklo",
  "Kad būtum laimingas, privalai būti protingas.<br>Sofoklis",
  "Kad apgintum savigarbą, kartais reikia meluoti ir apgaudinėti.<br>Robertas Birnis",
  "Joks pašnekovas jūsų nesiklausytų, jei nežinotų, kad paskui ateis jo eilė kalbėti.<br>E.V.Hau",
  "Joks didis dalykas pasaulyje neapsiėjo be aistros.<br>G.Hėgelis",
  "Jokie pinigai nebūna taip gerai panaudoti, kaip tie, kuriuos mums nusuko: už juos įsigyjame išminties.<br>A. Šopenhaueris",
  "Jokia nelaimė nėra per didelė, jei ji paskutinė.<br>Seneka",
  "Jeigu vienas kitas malonus žodis gali padaryti žmogų laimingą, reikia būti niekšu, kad šito nepadarytum.<br>V.Penas",
  "Jeigu uždarysite duris visoms klaidoms, tiesa liks už durų.<br>R.Tagorė",
  "Jeigu paslėpsite tiesą ir užkasite ją į žemę, ji būtinai išaugs ir įgis tokią jėgą, kad ištrūkusi nušluos viską savo kelyje.<br>E.Zola",
  "Jeigu padarysi neįmanoma, tai aišku viena, kad visa tai bosas įrašys į tavo pareigybių instrukciją.<br>Dougas Larsonas",
  "Jeigu laikote dramblį už užpakalinės kojos, o jis bando ištrūkti, geriausia jį paleisti.<br>A.Linkolnas",
  "Jeigu jaučiatės laimingas, neanalizuokite savo laimės: tai tas pats, kaip suplėšyti gražią peteliškę, kad būtų geriau matyti jos grožis.<br>P.Mantegaca",
  "Jeigu faktai neatitinka teorijos, pakeiskite faktus.<br>Albertas Einšteinas",
  "Jei žmogus sugeba mąstyti ir gali matyti saulę, mėnulį, žvaigždes, džiaugtis žemės gėrybėmis ir jūra, jis – ne vienišas ir ne bejėgis.<br>Epiktetas",
  "Jei žmogus padaro tą pačią klaidą du kartus, turi iškelti rankas aukštyn ir pripažinti savo lengvabūdiškumą arba užsispyrimą.<br>Dž.H.Lorimeras",
  "Jei visą laiką sakysi tiesą, tau nieko nereikės atsiminti.<br>Markas Twainas",
  "Jei tu kalbiesi su Dievu, tai vadinasi “melstis”, jei Dievas kalbasi su tavim, tai jau vadinasi šizofrenija.<br>Thomas Szaszas",
  "Jei nėra sielvarto gyvenime, nėra ir meilės gyvenimui.<br>A. Kamiu",
  "Jei nori su kuo nors pasitarti apie savo reikalus, pasidomėk, kaip sekasi jam pačiam.<br>Isokratas",
  "Jei nori jaunai atrodyti, reikia gyventi santūriai, po truputį valgyti ir meluoti apie savo amžių.<br>Liucilė Bol",
  "Jei kada nors, laimę vaikydamiesi, ją rasite, tai, panašiai kaip senė, ieškanti savo akinių, pastebėsite, kad ji visą laiką buvo jums ant nosies.<br>H.V.Šo",
  "Ir gera, ir bloga nuotaika dažniausiai valdoma žmogaus valios.<br>S.Smailsas",
  "Ilgai svarstantis ne visada randa geriausią sprendimą.<br>J.V.Getė",
  "Ieškoti tiesos – nereiškia ieškoti to, kas geidžiama.<br>Albertas Kamiu",
  "Idėjas galima nuginkluoti tik kitomis idėjomis.<br>H. de Balzakas",
  "Humoras – tai gelbėjimosi ratas gyvenimo bangose.<br>V.Rabė",
  "Gyventi su žmona nelengva, tačiau gyventi be jos – neįmanoma.<br>Katonas",
  "Gyvenkite taip, kad jums nebūtų gėda parduoti savo papūgą didžiausiam mieste liežuvautojui.<br>V.Rodžersas",
  "Gyvenk taip, lyg mirtum rytoj. Mokykis taip, lyg gyventum amžinai.<br>Gandhi",
  "Gyvenimo laiptai pilni rakščių, ir jos skaudžiausiai duria slenkant žemyn.<br>V.K.Braunelas",
  "Gyvenime yra tik dvi tragedijos: pirma yra negauti to, ko trokšti, antra – tai gauti.<br>Oskaras Vaildas",
  "Gyvenime labiausiai mums stinga žmogaus, kuris mus verstų daryti tai, ką mes mokame. R.V.Emersonas",
  "Gyvenime kai kam būna kaip pas dantų gydytoją – vis tikiesi, jog svarbiausias momentas dar tik bus, o jis jau praėjo.<br>Bismarkas",
  "Gyvenimas yra tai, kas atsitinka, kai jūs negalite užmigti.<br>Franas Lebovitzas",
  "Gyvenimas užkrečiamas – kaip ir liga.<br>Žoržas Sandas",
  "Gyvenimas – tai ne atostogos. Jei jūs įsisąmoninsite šį požiūrį, jūsų gyvenime atostogų bus pakankamai.<br>M.Ditrichas",
  "Gyvenimas – tai amžinybės miniatiūra.<br>R.V.Emersonas",
  "Gyvenimas – kalnas, į kurį kopi ilgai, o nusileidi greitai.<br>G. Mopasanas",
  "Geriems būti geram ir geram būti negeriems – štai didžiausias gerumas.<br>Lao Dzė",
  "Geriausias būdas nuraminti širdį – proto darbas.<br>G. de Levisas",
  "Gerbk tuos, kurie bandė atlikti didžius darbus, net jeigu jiems tai nepavyko.<br>Seneka",
  "Genijus – tai nesugebėjimas nieko neveikti.<br>Š.Diubo",
  "Džiaugsmas tai medis, ir kaip gaila, kad kiekvieno džiaugsmo šaknys tai liūdesys.<br>A.A.Maris",
  "Dėl savo nelaimių žmonės linkę kaltinti likimą, dievus ir ką tik nori, bet ne patys save.<br>Platonas",
  "Didžiausia nedorybė – imtis darbo, kurio nemoki.<br>Napoleonas",
  "Daugumas žmonių savo atmintį laiko intelektu, o savo požiūrį – faktais.<br>P.Masonas",
  "Dar nebuvo tokio žmogaus, kuris mirties patale apgailestautų, kad per mažai laiko praleido darbe.<br>Stefanas Kovis",
  "Dailininkas turi tik vieną priešą – nevykusius savo paties paveikslus.<br>A.Matisas",
  "Cezariui daug kas neleistina kaip tik todėl, kad jam leistina viskas.<br>Seneka",
  "Blogų poelgių reikia vengti dėl neapykantos jiems, o ne iš baimės.<br>Publilijus Siras",
  "Blogį gimdo troškimų gausumas.<br>Si-Ma Cjenas",
  "Baisiausias bet kurios visuomenės sutvėrimas yra žmogus, kuriam nėra ką prarasti.<br>Džeimsas Boldvinas",
  "Baimė suklysti neturi mūsų atbaidyti nuo tiesos ieškojimo.<br>K.A.Helvecijus",
  "Baimė – štai vienintelis dalykas, kurio turime bijoti.<br>T. Ruzveltas",
  "Aštrus liežuvis – vienintelis pjovimo įrankis, kuris vartojamas tampa dar aštresnis.<br>W.Irvingas",
  "Aš žinau žmogaus gyvenime tik dvi nelaimes: sąžinės graužimą ir ligą.<br>L.Tolstojus",
  "Aš niekada negalvoju apie ateitį – ji per greitai ateina.<br>Albertas Einšteinas",
  "Aristotelis tvirtino, kad moteris turi mažiau dantų negu vyrai, ir nors jis buvo du kartus vedęs, jam nešovė į galvą mintis patyrinėti savo žmonų burnų.<br>Bertrandas Ruselas",
  "Ankstesnės kartos paliko mums ne tiek parengtus atsakymus į klausimus, kiek pačius klausimus.<br>Seneka",
  "Akys neklysta, kol pasikliaujama savo paties, o ne kitų akimis.<br>A.Miunte",
  "Aistros suteikia proto kvailiausiems žmonėms ir paverčia kvailiais pruotinguosius.<br>Seneka",
  "Aistra – blogas reguliatorius, bet galinga spyruoklė.<br>R.V.Emersonas",
  "Šnekėti nemąstant – tai tas pats, kas šaudyti nesitaikant.<br>M. de Servantesas",
  "Nelaimingas tas, kuriame nėra nė trupinėlio Don Kichoto.<br>A.Fransas",
  "Šiame pasaulyje svarbiausia ne tai, kur stovime, o kuria kryptimi judame.<br>O.V. Holmsas",
  "Įsišaknijusios silpnybės panašios į musę: tu šimtus kartų ją nuvarai, o ji grįžta ir kankina tave vis labiau.<br>L.Eferis",
  "Senatvėje labiau sugebame nelaimių išvengti, jaunystėje – jas iškęsti.<br>A. Šopenhaueris",
  "Galbūt aš nenuėjau ten, kur ketinau, bet už tat sustojau ten, kur norėjau.<br>Douglas Adamsas",
  "Menas yra arba perversmas, arba plagiatas.<br>Polis Gogenas",
  "Svarbiausia, kad mūsų teisumas ir išmintis, atsiskleidę mums prieš akis, būtu su šaknimis išrauti iš mūsų širdžių bei mūsų išdidžios sielos.<br>Martinas Liuteris Kingas",
  "Ką jūs, vaikai, žinote apie būtį! Juk jūs bijote savo pačių jausmų. Jūs neberašote laiškų – jūs skambinate telefonu; jūs nebesvajojate – jūs važiuojate savaitgaliui į užmiestį; jūs esate protingi meilėje ir neprotingi politikoje – pasigailėjimo verta padermė! [Trys draugai]Erichas Marija Remarkas",
  "Kuo geriau ir prasmingiau nugyventas gyvenimas, tuo mažiau baisi jo pabaiga. Tik kai esame nepatenkinti nugyventu suprantame, kad iš naujo jo nenugyvensime, todėl baisi jo pabaiga.<br>Irvinas D. Jalomas",
  "Be kentėjimo koks gi būtų malonumas?<br>Fiodoras Dostojevskis",
  "Mirties aš nebijau. Tik mirties atėjimas mane baugina.<br>Oskaras Vaildas",
  "Viskas – niekas, o niekas yra niekas. Negali turėti visko, turi duoti, kad gauti atgal – tai vienintelis kelias. Kartais, regis, atiduodi viską, bet viskas – niekas, todėl atidavęs, gauni atgal viską, ko norėjai ir vėl ieškai, kas galėtų būti viskas. Tuomet svajoji ir atrandi naują nieką – tai, kas uždega akis liepsna ir padaro įmanomu viską. Saulė pakyla, tamsa dingsta, horizontas žaižaruoja ryškia šviesa, nušviesdamas tamsiausius kampelius. Svajonė veda tave už rankos, o Tu lyg mažas vaikas to nesupranti, bet nuoširdžiai džiaugiesi. Ji tave švelniai glosto palikdama visas negandas užmarštyje.<br>Mindaugas Bubelis",
  "Skelbti žmonių meilę- tai ją vykdyti. O vykdyti meilę- tai griauti pasaulį [Meilė, džiazas ir velnias]Juozas Grušas",
  "Kartą gimęs, pirmiausia apsiprask su neteisybe. Susigyvenk su ja. Tai būtina! O tu nori kovoti? Kovai reikia entuziazmą keliančių iėjų. Kitaip tariant,- baisiai didelio ir gražaus melo. [Meilė, džiazas ir velnias]Juozas Grušas",
  "Vien įkvėpimo poetui nepakanka , reikia išlavinto proto įkvėpimo.<br>Fridrichas Šileris",
  "Kiek dera turėti vaizduotės, kad išauklėtum tokius žmones, kurių reikia dabarčiai.<br>Nikolajus Gogolis",
  "Valia gali pakeisti net mūsų delnų linijas.<br>Žanas Kokto",
  "Kritika neturėtų būti pikta ir žeidžianti iki širdies gelmių; ji turėtų būti nukreipianti, pamokanti ir įkvepianti.<br>Ralfas Voldas Emersonas",
  "Auklėjimas, neugdantis troškimų, tvirkina sielą. Auklėtojas turi mokyti trokšti.<br>Anatolis Fransas",
  "Persistengti – nereiškia pasiekti tikslą.<br>Onorė de Balzakas",
  "Gėris visada priklauso nuo dviejų sąlygų: nuo įvairios veiklos galutinio tikslo tinkamo iškėlimo ir nuo tinkamų priemonių tam tikslas siekti parinkimo.<br>Aristotelis",
  "Žmogus kilnusis, kuris turi šalį valdyti, nieko atkakliai laikytis neturi, nei nieko iš anksto atmesti, o visada būti to, kas teisinga, šalininku.<br>Konfucijus",
  "Ar vien pareigas einant galima valdyti?<br>Konfucijus",
  "Jei pats valdovas atsikratys geidulių, tai niekas jo šalyje nevogs, net jeigu vagys būtų apdovanojami.<br>Konfucijus",
  "Jei valdovas gerbia papročius, jam lengva valdyti liaudį.<br>Konfucijus",
  "Kai valdovas supamas pagyrų ir pataikavimų, o gerų patarimų negauna, šalos pavojuje.<br>Mo Ti",
  "Valdyti reikia mokėti.<br>Mo Ti",
  "Kai miesto sienos taisomos, daug būna nuvargusių, bet niekas nekrinta išsekęs. Kai mokesčiai renkami pagal paproti, daugelis praranda didžiules sumas, bet niekas nejaučia širdgėlos.<br>Mo Ti",
  "Nedaug yra valdovų, kurie, nesirūpindami doraisiais ir niekindami mokytojus, pajėgtų išlaikyti valdžią.<br>Mo Ti",
  "Žmogus retai kada gali priversti save mylėti, bet priversti gerbti save gali visuomet.<br>Bernaras de Fontenelis",
  "Koks žmogus, parodęs didvyriškumo, kilnumo, nuoširdumo, gali pasakyti, kad pats iš to nelaimėjo?<br>Henris Deividas Toras",
  "Gėris – ne mokslas, o veiksmas.<br>Romainas Rolandas",
  "Gelbstint žmogų leistina sukelti jam ir skausmą.<br>Publijus Siras",
  "Ką gerbiame, tam niekuomet nepataikaujame dėl to, kad pagarba vertinama, o iš meilikavimo pasišaipoma.<br>Publijus Siras",
  "Ar ne geriau užsitarnauti šlovę savo paties darbais, negu kitais žmonėmis naudotis.<br>Vang Čungas",
  "Jeigu nori kietai miegoti, gulk į patalą su švaria sąžine.<br>Bendžaminas Franklinas",
  "Ne klaidos taisymas, o atkaklus jos laikymasis žemina bet kurio žmogaus ar žmonių organizacijos garbę.<br>Bendžaminas Franklinas",
  "Kuo garsiau jis įrodinėjo savo garbę, tuo sparčiau mes skaičiavome savo stalo sidabrą.<br>Ralfas Voldas Emersonas",
  "Gėda ir garbė – kaip drabužiai: kuo labiau nuskarę, tuo mažiau jais rūpinamasi.<br>Apulėjus",
  "Melas – plonasienis daiktas; gerai įsižiūrėjus, jis persišviečia.<br>Seneka",
  "Nėra gėdingesnės vergijos už savanorišką.<br>Seneka",
  "Prarastos gėdos nesusigrąžinsi.<br>Seneka",
  "Būti subrendusiam yra viskas.<br>Viljamas Šekspyras",
  "Dėkingumas ne visada iškalbingas.<br>Volteras",
  "Kiekvienas šeimos tėvas turi būti šeimininku savo, o ne kaimyno namuose.<br>Volteras",
  "Ne nelygybė gniuždo, o priklausomybė.<br>Volteras",
  "Niekingi žmonės puikuojasi nuolat kalbėdami apie save, žymūs žmonės – niekados apie save nekalbėdami.<br>Volteras",
  "Nuobodybė – pats didžiausias mūsų priešas.<br>Volteras",
  "Gražiausi sumanymai žlunga dėl vykdytojų menkystės.<br>Brechtas",
  "Išreikštos mintys visados yra negyvos.<br>H.Hesė",
  "Mokėkite myleti meną savyje, o ne save mene.<br>K.Stanislavskis",
  "Meną reikia jausti, o ne suprasti.<br>R. de Gurmonas",
  "Menas visada buvo puikus visuomeninės santvarkos veidrodis.<br>R.Vagneris",
  "Scenoje žmogus turi būti laipteliu aukščiau negu gyvenime.<br>K.L.Biorne",
  "Žmogus laisvas tada, kai jis gali tai, ko nori, bet jis nelaisvas norėti: neįsivaizduojama, kad jis norėtų be priežasties.<br>Volteras",
  "Kūrybai reikia kantrybės, be jos nieko nepasiekiama.<br>N.Gogolis",
  "Menas – tai žmonijos sąžinė.<br>F.Hebelis",
  "Išlaisvink žmogų, ir pradės kurti.<br>A. de Sent Egziuperi",
  "Niekuomet žmogus nėra toks gražus, koks jis būna kurdamas.<br>Vydūnas",
  "Ieškoti tiesos – nereiškia ieškoti to, kas geidžiama.<br>A.Kamiu",
  "Menininkas priklauso savo laikui, gyvena jo teisėmis ir įpročiais; laikosi jo pažiūrų ir sampratos.<br>G.F.Hėgelis",
  "Meno kūrinys būtinai turi išreikšti kokią nors didžią. Nuostabu tik tai, kas rimta.<br>A.Čechovas",
  "Menas – tai mūšis. Mene nereikia savęs tausoti.<br>Ž.Mišlė",
  "Tikras menas aplenkia laiką.<br>R.Sen Pocis",
  "Nemokėti pradžiuginti sielos – reiškia ją parduoti.<br>A.Kamiu",
  "Gyvenimas pats savaime nėra nei gėris, nei blogis, o tik jų buveinė; koks jis bus, priklausys nuo mūsų pačių.<br>M.de Montenis",
  "Tai, ką sunku padaryti, reikia daryti su didžiausiu atkaklumu.<br>Konfucijus",
  "Matyti galima tik širdimi. Tai, kas svarbiausia, akimis nematome.<br>A.de Sent-Egziuperi",
  "Mes esame tikrai laisvi, kai išsaugojame sugebėjimą svarstyti savarankiškai, kai būtinybė nepriverčia mus ginti svetimų nuomonių.<br>Ciceronas",
  "Melas – plonasienis daiktas; gerai įsižiūrėjus, jis persišviečia.<br>Seneka",
  "Spartinti normalią laiko tėkmę – labai brangus dalykas. Tad žiūrėkime, kad nereikėtų jam mokėti palūkanų.<br>A.Šopenhaueris",
  "Kiekvienas gyvenimas – tai pastangos ir kova už teisę būti pačiu savimi.<br>Ch.Ortega I Gasetas",
  "Žmonės žaidžia gyvenimą – kuo tragiškesnė kaukė, tuo didesnis juokdarys po ja slepiasi.<br>Ch.Ortega I Gasetas",
  "Tikroji gyvenimo pilnatvė – ne pasitenkinimo ramybė, o tikslo siekimo procesas, jo įtvirtinimo akimirka.<br>Ch.Ortega I Gasetas",
  "Kai buvęs idealas tampa kasdienine tikrove, jis neišvengiamai žūva.<br>Ch.Ortega I Gasetas",
  "Tiek aukščiausia, tiek ir žemiausia kritikos forma – savotiška autobiografija.<br>O.Vaildas",
  "Tai, kuo neabejoji, visada būna netikra. Kaip tik dėl to tikėjimas toks lemtingas, o romantika tokia pamokanti.<br>O.Vaildas",
  "Menininkas tampa savimi nuolat eidamas nuo savęs prie kitų ir nuo kitų prie savęs, jis visados yra pusiaukelėje tarp grožio, be kurio negali apsieiti, ir bendrijos, iš kurios negali ištrukti. Štai kodėl tikri menininkai nieko nesmerkia, užuot teisę, jie įsipareigoja suprasti.<br>A.Kamiu",
  "Jeigu menininkas nesutramdo savęs pats, jis paklaiksta ir ima vergauti šmėkloms.<br>A.Kamiu",
  "Nuosprendis, kurį jūs sviedžiate kitiems, apsisuka ir grįžta atgal, tiesiai jums į veidą, šiek tiek jį sužeisdamas.<br>A.Kamiu",
  "Kai matai, kiek tave yra aplenkusių, pagalvok, kiek nuo tavęs atsilikusių.<br>Seneka",
  "Nė vienas iš žmogiškų dalykų nėra vertas, kad dėl jo labai sielvartautum.<br>Platonas",
  "Susikaupk! Protas, kuris tave valdo, jaučia pasitenkinimą, kai elgiesi teisingai, dėl to išlaiko vidinę ramybę.<br>Markas Aurelijus",
  "Geriems būti geram ir geram būti negeriems – štai didžiausias gerumas.<br>Lao Dzė",
  "Vaikų lūpomis sakoma tiesa.<br>Žanas Polis Sartras",
  "Suvokdami tiesą, mes džiaugiamės. O jei džiaugsmo nėra, vadinasi, mes tik pažinome tiesą, bet nesugebėjome jos suvokti.<br>Rabindranatas Tagorė",
  "Tam, kuris ilgai mąsto apie tai, kaip daryti gera, nelieka laiko būti geram.<br>Rabindranatas Tagorė",
  "Gera tik visiška tiesa. Pusė tiesos nieko neverta.<br>Stefanas Cveigas",
  "Perdėjimas yra gerai išauklėtų žmoniu melas.<br>Žozefas Mestras",
  "Kuo labiau išvystytas protas, tuo aiškiau jis suvokia, kad teisingumas – vienintelis kelias į laimę.<br>Stendalis",
  "Kai visos kitos teiseės sutryptos, teisė sukilti tampa neginčyjama.<br>Tomas Peinas",
  "Kas širdimi geras, tas ir prastu drabužiu kilnus.<br>Gustavas Freitagas",
  "Nepaklusti jokiam įstatymui – vadinasi, neturėti visų patikimiausios apsaugos, nes įstatymai turi mus ginti ne tik nuo kitų, bet ir nuo savęs pačių.<br>Heinrichas Heinė",
  "Jeigu paslėpsite tiesą ir užkasite ją į žemę, ji būtinai išaugs ir įgis tokią jėgą, kad ištrūkusi nušluos viską savo kelyje.<br>Emilis Zola",
  "Yra ginklas, siaubingesnis už šmeižta,– tai tiesa.<br>Taleiranas",
  "Teismas yra kilnių ir įžymių elgetų asamblėja.<br>Taleiranas",
  "Tikėk tais, kurie ieško tiesos. Netikėk tais, kurie rado.<br>Andrė Židas",
  "Tai yra teisėta, kadangi aš to noriu.<br>Liudvikas XIV",
  "Įstatymas yra gėrio ir teisingumo menas.<br>Domicijus Ulpianas",
  "Kas pamalonina princa turi įstatymo galia.<br>Domicijus Ulpianas",
  "Teisingumas yra pastovi ir amžina jėga, kuri duoda kiekvienam žmogui tas kas priklauso.<br>Domicijus Ulpianas",
  "Visas tiesas lengva suprasti, kai jos atrastos. Svarbu jas rasti.<br>Galilėjus Galilėjas",
  "Bet kokia tiesa geriau už apsimetimą.<br>Henris Davidas Thoreau",
  "Nenuvertinkime fakto reikšmės: kada nors jis išskleis tiesos žiedą.<br>Henris Davidas Thoreau",
  "Neteisingumas ne visada susijęs su kokiu nors veiksmu; dažnai tai kaip tik yra neveiklumas.<br>Markas Aurelijus",
  "Jei sakote tik tiesą, jums nereikia nieko atsiminti.<br>Markas Tvainas",
  "Tiesumas puošia visus jo lydimus jausmus.<br>Žanas Žakas Ruso",
  "Kai dingsta teisingumas, niekas nebepadarys žmonių gyvenimo vertingo.<br>Imanuelis Kantas",
  "O kas, po galais, yra teisinga? Nepasakytum? Atvirai sakant, man nelabai aišku, kas yra teisinga. Kas yra neteisinga – suprantu. Bet kas yra teisinga? (Mylimoji Sputnik)<br>Harukis Murakamis",
  "Išgelbėti pasauliui užtenka, kad kiekvienas, nors ir visiškai mažas, išdrįstų pradėti.<br>Brunas Fereras",
  "Paskala ne visada klysta<br>Tacitas",
  "Geri įstatymai turi savo kilmę blogoje moralėje.<br>Makrobijus",
  '<em><span style="text-decoration: underline;">Žymūs žmonės kalba &nbsp;apie madą:</span></em>',
  '<span style="font-size: small;">Būti madingu, nereiškia išsiskirti. Būti madingu reiškia būti pastebėtu ir išlikti pastebėjusio atmintyje.</span>',
  "<em><strong>&nbsp;Giorgio Armani</strong></em>",
  "Ar žinote, kas finansų krizės metu išgelbės madą? Italijos ūkininkai. Mada ir etnogastronomija šiandien eina koja kojon. Išgėrę Milano auksiniame kvadrate brangaus vyno ir paragvę Viduržemio jūros virtuvės rusų, japonų ir amerikiečių klientai atsipalaiduos ir pirks.",
  "<em><strong>Guglielmas Miani, Milano „Montenapoleone“&nbsp;</strong></em>",
  "Moterys visais laikais sureikšmindavo deimantus. Tik deimantų irgi būna įvairių, priklauosomai nuo to, kur jie iškasami.",
  "<strong><i>Deimantų kūrėjas Robertas Koinas</i></strong>",
  "<strong>&nbsp;</strong>Bijo ateities tik nešvarios sąžinės žmonės. Aš labiau už viską vertinu ne turtą, o žmones. Nė vieno savo darbuotojo krizės metu neatleidau, juk turėčiau išardyti šeimas. O kam? Kad tapčiau kapinių turtingiausiuoju.",
  "<strong><i>Brunel</i></strong><strong><i>as</i></strong><i></i><strong><i>K</i></strong><strong><i>ucinelis,&nbsp; mados namų „Brunello Cucinelli“&nbsp;savininkas</i></strong>",
  "<strong>&nbsp;</strong>Nebijau ant podiumo pasirodyti vien su apatinėmis kelnaitėmis. Esu disciplinos vergas, sportuoju, todėl džiaugiuosi savo atletiška išvaizda. Užlipti ant pakylos –&nbsp; įdomus iššūkis.",
  "<strong><i>Praeityje garsus Italijos futbolininkas, „Dirk Bikkembergs“&nbsp;mados namų modelis Fabrizi</i></strong><strong><i>jus</i></strong><strong><i> Ravanelis</i></strong>",
  "<strong>&nbsp;</strong>Arvirai kalbėdamas apie „bunga – bunga“&nbsp;premjeras S. Berlusconi pažemino moteris. Aš kuriu aukštosios mados drabužius trims kartoms&nbsp; – močiutėms, mamoms, anūkėms. Visas jas vertinu ir išaukštinu, tai ne šiaip sau objektai skirti vyrams gundyti. Mano klientės – „donna di classe“&nbsp;– (it. elegantiška, kilminga, didinga moteris).",
  "<strong><i>Rafaela </i></strong><strong><i>K</i></strong><strong><i>uriel, aukštosios mados dizainerė</i></strong>",
  "<strong>&nbsp;</strong>Kiek daug beuždirbtų manekenė, ji niekada neturi pamiršti, kad didžiausias turtas tai – nepriklausyti nuo vyro.",
  "<strong><i>&nbsp;Divina Alighieri, legendinė aukštosios mados manekenė</i></strong>",
  "<strong>&nbsp;</strong>Pasaulinės mados fone italus išskiria jų „eccellenza“ – (it. geriau už labai gerai). Tai reiškia,kad mokame būti matomi minioje, išreikšti save ir emocijas. Madoje būtent tai – svarbiausia.",
  "<strong><i>Erman</i></strong><strong><i>as</i></strong><strong><i> Scervin</i></strong><strong><i>as</i></strong><strong><i>, nišinės mados kūrėjas iš Toskanos</i></strong>",
  "<strong>&nbsp;</strong>Re Giorgio drabužis ne tik papuošia, jis atskleidžia asmenybę, ją tarsi apnuogina.",
  "<strong><i>Violante Placido, aktorė, dizainerio Giorgio Armani klientė</i></strong>",
  "<strong>&nbsp;</strong>Manekenė – tai gyva dizainerio rūbų reklama. Iš mados kūrėjų esu gavusi nemažai dovanų. Matyt, gerai juos reklamuoju,&nbsp; nė vieno dar nenuvyliau.",
  "<i>Aukštosios mados legendinis modelis Nadeige</i>"
];
